languageCode = "en-ja"
languageName = "English"
displayName = ""
isoCode = "en"
weight = 1
rtl = false

title = "Kota Nakamura"
# logo = "img/cube-3d.png"
description = "I am a Ph.D. student at Osaka University, Japan. My research focuses on data mining esp. time series and tensor streams." 
#copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "May 2023"


[author]
  name = "Kota Nakamura"
  image = "img/prof_kota_official.JPG"  #1860x1860
  headline = "" 
  links = [
     { github = "https://github.com/kotaNakm" },
     { email = "mailto:kota88@sanken.osaka-u.ac.jp" },
     { twitter = "https://twitter.com/kotanakm" },
     { linkedin = "https://www.linkedin.com/in/kota-nakamura-9868591ba/" },
     { youtube = "https://youtube.com/@kotaNakm" },
  #   { link = "https://link-to-some-website.com/" },
  #   { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
  #   { apple = "https://www.apple.com" },
  #   { blogger = "https://username.blogspot.com/" },
  #   { codepen = "https://codepen.io/username" },
  #   { dev = "https://dev.to/username" },
  #   { discord = "https://discord.gg/invitecode" },
  #   { dribbble = "https://dribbble.com/username" },
  #   { facebook = "https://facebook.com/username" },
  #   { flickr = "https://www.flickr.com/photos/username/" },
  #   { foursquare = "https://foursquare.com/username" },
  #   { gitlab = "https://gitlab.com/username" },
  #   { google = "https://www.google.com/" },
  #   { hashnode = "https://username.hashnode.dev" },
  #   { instagram = "https://instagram.com/username" },
  #   { keybase = "https://keybase.io/username" },
  #   { kickstarter = "https://www.kickstarter.com/profile/username" },
  #   { lastfm = "https://lastfm.com/user/username" },
  #   { mastodon = "https://mastodon.instance/@username" },
  #   { medium = "https://medium.com/username" },
  #   { microsoft = "https://www.microsoft.com/" },
  #   { orcid = "https://orcid.org/userid" },
  #   { patreon = "https://www.patreon.com/username" },
  #   { pinterest = "https://pinterest.com/username" },
  #   { reddit = "https://reddit.com/user/username" },
  #   { researchgate = "https://www.researchgate.net/profile/username" },
  #   { slack = "https://workspace.url/team/userid" },
  #   { snapchat = "https://snapchat.com/add/username" },
  #   { soundcloud = "https://soundcloud.com/username" },
  #   { stack-overflow = "https://stackoverflow.com/users/userid/username" },
  #   { steam = "https://steamcommunity.com/profiles/userid" },
  #   { telegram = "https://t.me/username" },
  #   { tiktok = "https://tiktok.com/@username" },
  #   { tumblr = "https://username.tumblr.com" },
  #   { twitch = "https://twitch.tv/username" },
  #   { whatsapp = "https://wa.me/phone-number" },
  ]
    bio = "A little bit about you"

